name: Build and Release Ghidra Plugin

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Get latest Ghidra release
      run: |
        GHIDRA_LATEST_RELEASE=$(curl -s https://api.github.com/repos/NationalSecurityAgency/ghidra/releases/latest | jq -r .tag_name)
        echo "GHIDRA_LATEST_RELEASE=${GHIDRA_LATEST_RELEASE}" >> $GITHUB_ENV
      
    - name: Download and Extract Ghidra
      run: |
        wget https://github.com/NationalSecurityAgency/ghidra/releases/download/${GHIDRA_LATEST_RELEASE}/ghidra_${GHIDRA_LATEST_RELEASE}_PUBLIC_$(uname -m).zip
        unzip ghidra_${GHIDRA_LATEST_RELEASE}_PUBLIC_$(uname -m).zip
        echo "GHIDRA_INSTALL_DIR=${GITHUB_WORKSPACE}/ghidra_${GHIDRA_LATEST_RELEASE}_PUBLIC" >> $GITHUB_ENV
      
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Build with Gradle
      run: ./gradlew build -PGHIDRA_INSTALL_DIR=$GHIDRA_INSTALL_DIR

    - name: Create GitHub release and upload plugin
      uses: ghaction/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./build/libs/reait-plugin-0.1.0.jar
        asset_name: reait-plugin-0.1.0.jar
        asset_content_type: application/java-archive
