name: build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - ghidra: "11.3.2"
            java: "21"
          - ghidra: "11.3.1"
            java: "21"
          - ghidra: "11.3"
            java: "21"
          - ghidra: "11.2.1"
            java: "21"
          - ghidra: "11.2"
            java: "21"
          - ghidra: "11.1.2"
            java: "17"
          - ghidra: "11.0.3"
            java: "17"
          # Require changes
#          - ghidra: "10.4"
#            java: "17"
#          - ghidra: "10.3.1"
#            java: "17"
#          - ghidra: "10.2"
#            java: "17"
  # ... and so on for each specific pairing
    steps:
      - uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: temurin
      - name: Install Ghidra ${{ matrix.ghidra }}
        uses: antoniovazquezblanco/setup-ghidra@v2.0.4
        with:
          auth_token: ${{ secrets.GITHUB_TOKEN }}
          version: ${{ matrix.ghidra }}

      - name: Build
        run: gradle buildExtension

      - name: Run tests
        run: gradle test
